//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTUserNotification
    {
        public int NotificationID { get; set; }
        public int TSTUserID { get; set; }
        public int PostedBy { get; set; }
        public string Message { get; set; }
        public System.DateTime DateEntered { get; set; }
        public bool IsRead { get; set; }
        public Nullable<int> TicketID { get; set; }
    
        public virtual TSTTicket TSTTicket { get; set; }
        public virtual TSTUser TSTUser { get; set; }
        public virtual TSTUser TSTUser1 { get; set; }
    }
}
