//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSTEntities : DbContext
    {
        public TSTEntities()
            : base("name=TSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TSTComment> TSTComments { get; set; }
        public virtual DbSet<TSTMessage> TSTMessages { get; set; }
        public virtual DbSet<TSTProjectCategory> TSTProjectCategories { get; set; }
        public virtual DbSet<TSTProject> TSTProjects { get; set; }
        public virtual DbSet<TSTProjects_Users> TSTProjects_Users { get; set; }
        public virtual DbSet<TSTResolution> TSTResolutions { get; set; }
        public virtual DbSet<TSTTicketClassification> TSTTicketClassifications { get; set; }
        public virtual DbSet<TSTTicket> TSTTickets { get; set; }
        public virtual DbSet<TSTTicketStatus> TSTTicketStatuses { get; set; }
        public virtual DbSet<TSTUserContact> TSTUserContacts { get; set; }
        public virtual DbSet<TSTUserNotification> TSTUserNotifications { get; set; }
        public virtual DbSet<TSTUserPreference> TSTUserPreferences { get; set; }
        public virtual DbSet<TSTUser> TSTUsers { get; set; }
        public virtual DbSet<TSTUserTitle> TSTUserTitles { get; set; }
    }
}
