//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTResolution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTResolution()
        {
            this.TSTTickets = new HashSet<TSTTicket>();
        }
    
        public int ResolutionID { get; set; }
        public string Problem { get; set; }
        public string Resolution { get; set; }
        public int PostedBy { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string Attachment { get; set; }
    
        public virtual TSTUser TSTUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTicket> TSTTickets { get; set; }
    }
}
