//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTTicket()
        {
            this.TSTComments = new HashSet<TSTComment>();
            this.TSTUserNotifications = new HashSet<TSTUserNotification>();
        }
    
        public int TicketID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public int TicketClassificationID { get; set; }
        public int SubmittedBy { get; set; }
        public Nullable<int> TechAssigned { get; set; }
        public int TicketStatusID { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public Nullable<System.DateTime> DateResolved { get; set; }
        public int ProjectID { get; set; }
        public string Attachment1 { get; set; }
        public string Attachment2 { get; set; }
        public string Tags { get; set; }
        public Nullable<int> ResolutionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTComment> TSTComments { get; set; }
        public virtual TSTProject TSTProject { get; set; }
        public virtual TSTResolution TSTResolution { get; set; }
        public virtual TSTTicketClassification TSTTicketClassification { get; set; }
        public virtual TSTTicketStatus TSTTicketStatus { get; set; }
        public virtual TSTUser TSTUser { get; set; }
        public virtual TSTUser TSTUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTUserNotification> TSTUserNotifications { get; set; }
    }
}
