//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTUserPreference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTUserPreference()
        {
            this.TSTUsers = new HashSet<TSTUser>();
        }
    
        public int UserPreferenceID { get; set; }
        public string DisplayName { get; set; }
        public bool ShowStreetAddress { get; set; }
        public bool ShowCityState { get; set; }
        public bool ShowZip { get; set; }
        public bool ShowCountry { get; set; }
        public bool ShowEmail { get; set; }
        public bool ShowBirthday { get; set; }
        public bool EmailNotifications { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTUser> TSTUsers { get; set; }
    }
}
